### ISSUE TITLE
Tests fail with nightly

### ISSUE THREAD

**Issue by gwenn** [jgallagher/rusqlite#154]
rustc 1.10.0-nightly (9c6904ca1 2016-05-18)

```
---- Connection::transaction_0 stdout ----
	<anon>:7:19: 7:23 error: cannot borrow immutable borrowed content `*conn` as mutable
<anon>:7     let tx = try!(conn.transaction());
                           ^~~~
<anon>:7:19: 7:23 note: in this expansion of try! (defined in <std macros>)
error: aborting due to previous error(s)
thread 'Connection::transaction_0' panicked at 'Box<Any>', ../src/librustc/session/mod.rs:169
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- transaction::Transaction<'conn>::savepoint_0 stdout ----
	<anon>:6:19: 6:23 error: cannot borrow immutable borrowed content `*conn` as mutable
<anon>:6     let tx = try!(conn.transaction());
                           ^~~~
<anon>:6:19: 6:23 note: in this expansion of try! (defined in <std macros>)
<anon>:9:23: 9:25 error: cannot borrow immutable local variable `tx` as mutable
<anon>:9         let sp = try!(tx.savepoint());
                               ^~
<anon>:9     let tx = try!(conn.transaction());
                 ^~
<anon>:9:23: 9:25 note: in this expansion of try! (defined in <std macros>)
error: aborting due to previous error(s)
thread 'transaction::Transaction<'conn>::savepoint_0' panicked at 'Box<Any>', ../src/librustc/session/mod.rs:169

---- transaction::Transaction_0 stdout ----
	<anon>:7:19: 7:23 error: cannot borrow immutable borrowed content `*conn` as mutable
<anon>:7     let tx = try!(conn.transaction());
                           ^~~~
<anon>:7:19: 7:23 note: in this expansion of try! (defined in <std macros>)
error: aborting due to previous error(s)
thread 'transaction::Transaction_0' panicked at 'Box<Any>', ../src/librustc/session/mod.rs:169


failures:
    Connection::transaction_0
    transaction::Transaction<'conn>::savepoint_0
    transaction::Transaction_0

test result: FAILED. 23 passed; 3 failed; 1 ignored; 0 measured
```

**Comment by jgallagher** [comment]
Huh, I wonder why those doctests didn't fail on stable. They're definitely wrong now. Thanks!
