### ISSUE TITLE
Sanitize code

### ISSUE THREAD

**Issue by gwenn** [jgallagher/rusqlite#376]
Try to run [sanitizers](https://github.com/japaric/rust-san) on Travis CI:
```
RUSTFLAGS="-Z sanitizer=address" cargo test --target x86_64-unknown-linux-gnu --lib --features "backup blob chrono functions hooks limits load_extension serde_json trace"
RUSTFLAGS="-Z sanitizer=leak" cargo test --target x86_64-unknown-linux-gnu --lib --features "backup blob chrono functions hooks limits load_extension serde_json trace"
Currently, the following are failing (at least on my linux box):
```
RUSTFLAGS="-Z sanitizer=memory" cargo test --target x86_64-unknown-linux-gnu --lib --features "backup blob chrono functions hooks limits load_extension serde_json trace"
Uninitialized bytes in __interceptor_memchr at offset 14 inside [0x7020000000c0, 30)
==4670==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5630b3ae9ebe in std::sys::unix::memchr::memchr::h8a95f533d7b023f7 /checkout/src/libstd/sys/unix/memchr.rs:18:8
    #1 0x5630b3ae9ebe in std::memchr::memchr::hdc24297e0fd1714d /checkout/src/libstd/memchr.rs:35
    #2 0x5630b3ae9ebe in std::ffi::c_str::CString::_new::h50cbb792c282caa1 /checkout/src/libstd/ffi/c_str.rs:335
    #3 0x5630b3ae9ebe in std::ffi::c_str::CString::new::h6be2293e0ec1b8ab /checkout/src/libstd/ffi/c_str.rs:331
    #4 0x5630b3ae9ebe in std::sys::unix::fs::cstr::h7882e18364419fa2 /checkout/src/libstd/sys/unix/fs.rs:626
    #5 0x5630b3ae9ebe in std::sys::unix::fs::stat::h917c0dd1eacd427d /checkout/src/libstd/sys/unix/fs.rs:805
    #6 0x5630b32de7f7 in std::fs::metadata::h7212343df134cb85 /checkout/src/libstd/fs.rs:1478:4
    #7 0x5630b32de7f7 in term::terminfo::searcher::get_dbpath_for_term::h8660d89530bed784 /checkout/src/libterm/terminfo/searcher.rs:60
    #8 0x5630b32d448f in term::terminfo::TermInfo::from_name::he1d34e5677dcf6f2 /checkout/src/libterm/terminfo/mod.rs:99:8
    #9 0x5630b32d4275 in term::terminfo::TermInfo::from_env::h21907cb3c12139a6 /checkout/src/libterm/terminfo/mod.rs:85:24
    #10 0x5630b32d4e33 in _$LT$term..terminfo..TerminfoTerminal$LT$T$GT$$GT$::new::h9240bda451952389 /checkout/src/libterm/terminfo/mod.rs:244:8
    #11 0x5630b32d2777 in term::stdout::hb0a766d0cc8eb4de /checkout/src/libterm/lib.rs:77:4
    #12 0x5630b32addb4 in test::run_tests_console::hffb3205b1e80e3ff /checkout/src/libtest/lib.rs:887:23
    #13 0x5630b32aaded in test::test_main::h370fabaec02c2b37 /checkout/src/libtest/lib.rs:285:14
    #14 0x5630b32ab013 in test::test_main_static::h4371908c4b7768ef /checkout/src/libtest/lib.rs:319:4
    #15 0x5630b313146e in rusqlite::__test::main::h45b5e40482955158 (/home/vagrant/rusqlite/target/x86_64-unknown-linux-gnu/debug/deps/rusqlite-a00969dd75caf8f8+0x2f946e)
    #16 0x5630b30ba265 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hf8cb86519e3bc700 /checkout/src/libstd/rt.rs:74:33
    #17 0x5630b3aeaf32 in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h70037fd790ab37a8 /checkout/src/libstd/rt.rs:59:12
    #18 0x5630b3aeaf32 in _ZN3std9panicking3try7do_call17h926ffec16d41c60dE.llvm.5015789304246416287 /checkout/src/libstd/panicking.rs:310
    #19 0x5630b3b09909 in __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:105:7
    #20 0x5630b3aed635 in std::panicking::try::h67f1d06d236d7c6f /checkout/src/libstd/panicking.rs:289:12
    #21 0x5630b3aed635 in std::panic::catch_unwind::ha0011e44885e2196 /checkout/src/libstd/panic.rs:392
    #22 0x5630b3aed635 in std::rt::lang_start_internal::h633fea8de4d9c386 /checkout/src/libstd/rt.rs:58
    #23 0x5630b30ba18e in std::rt::lang_start::h3b9b3f424b4f9e15 /checkout/src/libstd/rt.rs:74:4
    #24 0x5630b31314e1 in main (/home/vagrant/rusqlite/target/x86_64-unknown-linux-gnu/debug/deps/rusqlite-a00969dd75caf8f8+0x2f94e1)
    #25 0x7f45a15b206a in __libc_start_main (/usr/lib/libc.so.6+0x2306a)
    #26 0x5630b2e84379 in _start (/home/vagrant/rusqlite/target/x86_64-unknown-linux-gnu/debug/deps/rusqlite-a00969dd75caf8f8+0x4c379)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /checkout/src/libstd/sys/unix/memchr.rs:18:8 in std::sys::unix::memchr::memchr::h8a95f533d7b023f7
```
```
RUSTFLAGS="-Z sanitizer=memory" cargo test --target x86_64-unknown-linux-gnu --lib --features "backup blob chrono functions hooks limits load_extension serde_json trace"
==================
WARNING: ThreadSanitizer: data race (pid=5299)
  Write of size 8 at 0x7b3c00007ad0 by main thread:
    #0 free /checkout/src/libcompiler_builtins/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:707:3 (rusqlite-a00969dd75caf8f8+0x1d7834)
    #1 core::ptr::drop_in_place::hdb2dea4109f39a6a /checkout/src/liballoc/alloc.rs:80:4 (rusqlite-a00969dd75caf8f8+0x26034e)
    #2 _$LT$std..sync..mpsc..mpsc_queue..Queue$LT$T$GT$$GT$::pop::h4f71cb551ef01473 /checkout/src/libstd/sync/mpsc/mpsc_queue.rs:109 (rusqlite-a00969dd75caf8f8+0x26034e)
    #3 std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hf8cb86519e3bc700 /checkout/src/libstd/rt.rs:74:33 (rusqlite-a00969dd75caf8f8+0x130c48)
    #4 std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h70037fd790ab37a8 /checkout/src/libstd/rt.rs:59:12 (rusqlite-a00969dd75caf8f8+0x590292)
    #5 _ZN3std9panicking3try7do_call17h926ffec16d41c60dE.llvm.5015789304246416287 /checkout/src/libstd/panicking.rs:310 (rusqlite-a00969dd75caf8f8+0x590292)
    #6 main <null> (rusqlite-a00969dd75caf8f8+0x162227)

  Previous write of size 8 at 0x7b3c00007ad0 by thread T3:
    #0 malloc /checkout/src/libcompiler_builtins/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:664:5 (rusqlite-a00969dd75caf8f8+0x1d73f7)
    #1 alloc::alloc::alloc::he16578017c35982e /checkout/src/liballoc/alloc.rs:62:4 (rusqlite-a00969dd75caf8f8+0x261745)
    #2 alloc::alloc::exchange_malloc::h84fc8f60029ff81d /checkout/src/liballoc/alloc.rs:157 (rusqlite-a00969dd75caf8f8+0x261745)
    #3 _$LT$std..sync..mpsc..mpsc_queue..Node$LT$T$GT$$GT$::new::hc0181d86f9df73cb /checkout/src/libstd/sync/mpsc/mpsc_queue.rs:62 (rusqlite-a00969dd75caf8f8+0x261745)
    #4 _$LT$std..sync..mpsc..mpsc_queue..Queue$LT$T$GT$$GT$::push::hae7ecd6765a7f307 /checkout/src/libstd/sync/mpsc/mpsc_queue.rs:83 (rusqlite-a00969dd75caf8f8+0x261745)
    #5 _$LT$std..sync..mpsc..shared..Packet$LT$T$GT$$GT$::send::ha7606741a24d2f7c /checkout/src/libstd/sync/mpsc/shared.rs:171 (rusqlite-a00969dd75caf8f8+0x261745)

  Thread T3 'backup::test::t' (tid=5303, finished) created by main thread at:
    #0 pthread_create /checkout/src/libcompiler_builtins/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:965:3 (rusqlite-a00969dd75caf8f8+0x1d85e5)
    #1 std::sys::unix::thread::Thread::new::h1fabab93d0dc5000 /checkout/src/libstd/sys/unix/thread.rs:78:18 (rusqlite-a00969dd75caf8f8+0x590cae)
    #2 std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hf8cb86519e3bc700 /checkout/src/libstd/rt.rs:74:33 (rusqlite-a00969dd75caf8f8+0x130c48)
    #3 std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h70037fd790ab37a8 /checkout/src/libstd/rt.rs:59:12 (rusqlite-a00969dd75caf8f8+0x590292)
    #4 _ZN3std9panicking3try7do_call17h926ffec16d41c60dE.llvm.5015789304246416287 /checkout/src/libstd/panicking.rs:310 (rusqlite-a00969dd75caf8f8+0x590292)
    #5 main <null> (rusqlite-a00969dd75caf8f8+0x162227)

SUMMARY: ThreadSanitizer: data race /checkout/src/liballoc/alloc.rs:80:4 in core::ptr::drop_in_place::hdb2dea4109f39a6a
==================
```

**Comment by gwenn** [comment]
For `use-of-uninitialized-value`, false positive:
See https://github.com/rust-lang/rust/issues/39610
And https://github.com/BurntSushi/ripgrep/issues/697
